# apiVersion: v1
# kind: Service
# metadata:
#   name: flasksvc
# spec:
#   type: NodePort
#   ports:
#   - port: 5000
#     protocol: TCP
#   selector:
#     app: flaskapp

apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  labels:
    app: flaskapp
spec:
  containers:
  - name: flaskapp
    image: hvdrk0/flaskapp:latest
    ports:
    - containerPort: 5000